# REMEMBER TO EDIT THIS BEFORE DEPLOY!!!

# the path to your blog's icon:
favicon: /favicon.png

# the path to manifest.json
manifest: /manifest.json

# show excerpt on post list
show_excerpt: true

# navigation config
nav:
  # the title displays in the upper left corner which won't change
  title: Stories & Letters
  # the items displays in the upper right corner
  items:
    # these items will display as a link
    Archives: /archives
    About: /about

# footer items
footer:
  # the title
  Blog:
    # the items after the title, display as links
    Blog: /
    Archives: /archives
    About: /about
  # also the title
  Projects:
    # the items
    Transmister: https://github.com/transmister
    CSS&JS Windows UWP XAML Controls: https://github.com/MrWillCom/css-and-js-windows-uwp-xaml-controls
    Theme Cupertino: https://github.com/MrWillCom/hexo-theme-cupertino
    GitHub Dark Mode: https://github.com/MrWillCom/github-dark-mode
  # the title
  Me:
    # items
    GitHub: https://github.com/MrWillCom
    CodePen: https://codepen.io/mrwillcom
    Patreon: https://www.patreon.com/MrWillCom
    Email: mailto:mr.will.com@outlook.com
# REMEMBER TO EDIT THIS BEFORE DEPLOY!!!
