# REMEMBER TO EDIT THIS BEFORE DEPLOY!!!

# the path to your blog's icon:
favicon: /favicon.png

# the path to manifest.json
manifest: /manifest.json

# show excerpt on post list
show_excerpt: true

# navigation config
nav:
  # the title displays in the upper left corner which won't change
  title: Stories & Letters
  # the items displays in the upper right corner
  items:
    # these items will display as a link
    Archives: /archives
    About: /about

# footer items
footer:
  # the title
  Blog:
    # the items after the title, display as links
    Blog: /
    Archives: /archives
    About: /about
  # also the title
  Media:
    # the items
    Photos: https://github.com/transmister
    Videos: https://github.com/MrWillCom/css-and-js-windows-uwp-xaml-controls
# REMEMBER TO EDIT THIS BEFORE DEPLOY!!!
